# Use root/example as user/password credentials
version: '3.6'

services:

  db:
    container_name: mysql
    image: mysql/mysql-server
    restart: always
    ports:
      - "3306:3306"
    # environment:
    #   - MYSQL_ROOT_HOST=172.%.%.%
    volumes:
      - /Users/rniesler/DockerVolumes/MySQL:/var/lib/mysql

  mongodb:
      container_name: mongo
      image: mongo
      restart: always
      ports:
        - "27017:27017"
      volumes:
        - /Users/rniesler/DockerVolumes/MongoDB:/data/db
