# Use root/example as user/password credentials
version: '3.6'

services:
  oracledb:
    container_name: oracledb
    image: oracle/database:12.2.0.1-se2
    volumes:
      - /Users/rniesler/DockerVolumes/Oracle:/opt/oracle/oradata 
    ports:
      - 1521:1521
      - 5500:5500
